apiVersion: apps/v1
kind: Deployment
metadata:
  name: min
spec:
  replicas: 1
  selector:
    matchLabels:
      app: min
  template:
    metadata:
      labels:
        app: min
    spec:
      containers:
      - image: okteto.dev/min:latest
        name: min
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "aa755d1b-06fb-4303-9d33-a58e88a7caed"
        - name: Vless_Path
          value: "/vltr3"
        - name: Vmess_UUID
          value: "3483e99a-40be-43c8-a39d-42411c43e463"
        - name: Vmess_Path
          value: "/vmc36"
        - name: Share_Path
          value: "/v2link"
